# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'R10' do
 rn_path = '../node_modules/react-native'

    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    

    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    
end




